### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by shadowzoom** [dfaker/df#4]
When im trying to run align_images_masked.py
im getting
Traceback (most recent call last):
  File "align_images_masked.py", line 2, in <module>
    import cv2
  File "C:\Users\Admin\Anaconda3\lib\site-packages\cv2\__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: DLL load failed: %1 is not a valid Win32 application.
What the problem?

**Comment by dfaker** [comment]
Seems like your opencv installation is faulty in some way, I assume a simple "import cv2" fails in the exact same way?
