### ISSUE TITLE
 merge_faces_larger.py TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by hoaxherold** [dfaker/df#41]
Hi,

I would like to for help with the following problem:
merge_faces_larger.py says:

2018-10-04 19:23:05.077752: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "merge_faces_larger.py", line 244, in <module>
    main( parser.parse_args() )
  File "merge_faces_larger.py", line 202, in main
    for image_file, face_file, mat,facepoints in tqdm( alignments[args.startframe::args.frameSkip] ):
TypeError: unhashable type: 'slice'

tqdm is 4.26.0

Could you please help me what could be the problem?
Thank you!
Br,Herold

**Comment by hoaxherold** [comment]
problem solved. dfaker requires other json format than faceswap generated.
