### ISSUE TITLE
What do I write in the command line with align_images_masked.py?

### ISSUE THREAD

**Issue by MotorCityCobra** [dfaker/df#42]

**Comment by MotorCityCobra** [comment]
No idea how I'm the only one who can't figure this out.  

I try with one dir of photos. It puts images in a new folder with cropped faces with no alignments file.  

I write it with mask face and target face dir and I get this... 


$ python align_images_masked.py /home/eagle/Aly/tara/vids/sampled /home/eagle/k_and_a/yocon
  0%|                                                  | 0/5921 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "align_images_masked.py", line 125, in <module>
    main( parser.parse_args() )
  File "align_images_masked.py", line 102, in main
    face_alignments = list( iter_face_alignments() )
  File "align_images_masked.py", line 100, in iter_face_alignments
    yield str(fn.relative_to(input_dir)), str(out_fn.relative_to(input_dir)), list( alignment.ravel() ), list(points.flatten().astype(float))
  File "/home/eagle/anaconda3/envs/fastai/lib/python3.6/pathlib.py", line 870, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/home/eagle/k_and_a/yocon/4934-874a8e0d-e861-4f83-b982-00d1e275635a-92d2cda1-cc54-4a8d-af57-043b68733c28.jpg' does not start with '/home/eagle/Aly/tara/vids/sampled'

**Comment by MotorCityCobra** [comment]
Figured it out.  
One of my folders didn't contain jpgs, just pngs.  
and I didn't know the alignments json stayed in the original dir.
